[package]
name = "tm-rust-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
const-cstr = "0.3.0"
tracing = "0.1.26"
ultraviolet = "0.8.1"
machinery = { path = "../crates/machinery" }
machinery-api = { path = "../crates/machinery-api" }
