[package]
name = "example"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1.26"
machinery = { path = "../machinery" }
machinery-sys = { path = "../machinery-sys" }
