[projects.foundation]
headers = "$TM_SDK_DIR/headers/foundation"
headers_prefix = "foundation"
target = "./crates/machinery-api/src/foundation.rs"
uses = ["crate::plugins::ui::Draw2dFontT"]
blocklist = ["tm_draw2d_font_t"]

[projects.plugins-entity]
headers = "$TM_SDK_DIR/headers/plugins/entity"
headers_prefix = "plugins/entity"
target = "./crates/machinery-api/src/plugins/entity.rs"
uses = ["crate::foundation::*"]

[projects.plugins-renderer]
headers = "$TM_SDK_DIR/headers/plugins/renderer"
headers_prefix = "plugins/renderer"
target = "./crates/machinery-api/src/plugins/renderer.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::ui::UiStyleT",
]
blocklist = ["tm_ui_style_t"]

[projects.plugins-shader_system]
headers = "$TM_SDK_DIR/headers/plugins/shader_system"
headers_prefix = "plugins/shader_system"
target = "./crates/machinery-api/src/plugins/shader_system.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::renderer::*",
    "crate::plugins::render_graph::RenderGraphO",
]
blocklist = ["tm_render_graph_o"]

[projects.plugins-render_graph]
headers = "$TM_SDK_DIR/headers/plugins/render_graph"
headers_prefix = "plugins/render_graph"
target = "./crates/machinery-api/src/plugins/render_graph.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::renderer::*",
    "crate::plugins::shader_system::*",
    "crate::plugins::ui::{UiStyleT, ToolbarI}",
]
blocklist = ["tm_ui_style_t", "tm_toolbar_i"]

[projects.plugins-ui]
headers = "$TM_SDK_DIR/headers/plugins/ui"
headers_prefix = "plugins/ui"
target = "./crates/machinery-api/src/plugins/ui.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::renderer::*",
    "crate::plugins::shader_system::*",
    "crate::the_machinery::TabCreateContextT",
]
blocklist = ["tm_tab_create_context_t"]

[projects.plugins-simulate_common]
headers = "$TM_SDK_DIR/headers/plugins/simulate_common"
headers_prefix = "plugins/simulate_common"
target = "./crates/machinery-api/src/plugins/simulate_common.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
]

[projects.plugins-simulate]
headers = "$TM_SDK_DIR/headers/plugins/simulate"
headers_prefix = "plugins/simulate"
target = "./crates/machinery-api/src/plugins/simulate.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::renderer::*",
    "crate::plugins::ui::*",
    "crate::plugins::simulate_common::*",
]

[projects.plugins-graph_common]
headers = "$TM_SDK_DIR/headers/plugins/graph_common"
headers_prefix = "plugins/graph_common"
target = "./crates/machinery-api/src/plugins/graph_common.rs"
uses = [
    "crate::foundation::*",
]

[projects.plugins-editor_views]
headers = "$TM_SDK_DIR/headers/plugins/editor_views"
headers_prefix = "plugins/editor_views"
target = "./crates/machinery-api/src/plugins/editor_views.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::ui::*",
]

[projects.plugins-graph_interpreter]
headers = "$TM_SDK_DIR/headers/plugins/graph_interpreter"
headers_prefix = "plugins/graph_interpreter"
target = "./crates/machinery-api/src/plugins/graph_interpreter.rs"
prefix_headers = ["plugins/editor_views/graph.h"]
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::editor_views::*",
]

[projects.plugins-the_machinery_shared]
headers = "$TM_SDK_DIR/headers/plugins/the_machinery_shared"
headers_prefix = "plugins/the_machinery_shared"
target = "./crates/machinery-api/src/plugins/the_machinery_shared.rs"
prefix_headers = ["foundation/the_truth.h"]
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::ui::*",
    "crate::plugins::editor_views::*",
    "crate::plugins::renderer::*",
    "crate::plugins::shader_system::*",
    "crate::plugins::render_graph::*",
    "crate::plugins::simulate::*",
]

[projects.plugins-creation_graph]
headers = "$TM_SDK_DIR/headers/plugins/creation_graph"
headers_prefix = "plugins/creation_graph"
target = "./crates/machinery-api/src/plugins/creation_graph.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::renderer::*",
    "crate::plugins::shader_system::*",
    "crate::plugins::render_graph::*",
    "crate::plugins::ui::*",
    "crate::plugins::editor_views::*",
    "crate::plugins::the_machinery_shared::*"
]

[projects.the_machinery]
headers = "$TM_SDK_DIR/headers/the_machinery"
headers_prefix = "the_machinery"
target = "./crates/machinery-api/src/the_machinery.rs"
prefix_headers = ["plugins/ui/docking.h"]
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::ui::*",
    "crate::plugins::editor_views::*",
    "crate::plugins::the_machinery_shared::*",
    "crate::plugins::renderer::*",
]
