[projects.foundation]
headers = "$TM_SDK_DIR/headers/foundation"
headers_prefix = "foundation"
target = "./crates/machinery-api/src/foundation.rs"
uses = ["crate::plugins::ui::Draw2dFontT"]
blocklist = ["tm_draw2d_font_t"]

[projects.plugins-entity]
headers = "$TM_SDK_DIR/headers/plugins/entity"
headers_prefix = "plugins/entity"
target = "./crates/machinery-api/src/plugins/entity.rs"
uses = ["crate::foundation::*"]

[projects.plugins-ui]
headers = "$TM_SDK_DIR/headers/plugins/ui"
headers_prefix = "plugins/ui"
target = "./crates/machinery-api/src/plugins/ui.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::the_machinery::TabCreateContextT",
]
blocklist = ["tm_tab_create_context_t"]

[projects.plugins-editor_views]
headers = "$TM_SDK_DIR/headers/plugins/editor_views"
headers_prefix = "plugins/editor_views"
target = "./crates/machinery-api/src/plugins/editor_views.rs"
uses = [
    "crate::foundation::*",
    "crate::plugins::ui::*",
]

[projects.plugins-the_machinery_shared]
headers = "$TM_SDK_DIR/headers/plugins/the_machinery_shared"
headers_prefix = "plugins/the_machinery_shared"
target = "./crates/machinery-api/src/plugins/the_machinery_shared.rs"
prefix_headers = ["foundation/the_truth.h"]
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::ui::*",
    "crate::plugins::editor_views::*",
]

[projects.the_machinery]
headers = "$TM_SDK_DIR/headers/the_machinery"
headers_prefix = "the_machinery"
target = "./crates/machinery-api/src/the_machinery.rs"
prefix_headers = ["plugins/ui/docking.h"]
uses = [
    "crate::foundation::*",
    "crate::plugins::entity::*",
    "crate::plugins::ui::*",
    "crate::plugins::editor_views::*",
    "crate::plugins::the_machinery_shared::*",
]
