[package]
name = "machinery-api"
version = "0.3.1"
license = "MIT OR Apache-2.0"
description = "Generated API types for The Machinery game engine"
repository = "https://gitlab.com/celphase/machinery-rs"
edition = "2018"

[dependencies]
const-cstr = "0.3.0"
