[package]
name = "machinery"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.8.0"
unsafe_unwrap = "0.1.0"
machinery-sys = { path = "../machinery-sys" }

[build-dependencies]
syn = { version = "1.0.73", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
heck = "0.3.3"
