[package]
name = "machinery"
version = "0.1.0"
edition = "2018"

[dependencies]
unsafe_unwrap = "0.1.0"

[build-dependencies]
syn = { version = "1.0.73", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.27"
heck = "0.3.3"
